In [69]:
!nvidia-smi

Thu Apr 13 14:33:56 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro M4000M       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P5    12W / 100W |   1441MiB /  4096MiB |     15%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

# Some information about study
1. https://github.com/mrdbourke/pytorch-deep-learning/discussions
2. https://www.learnpytorch.io/

In [70]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0


In [71]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [72]:
scalar.ndim

0

In [73]:
# Get tensor back as Python int
scalar.item()

7

In [74]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [75]:
vector.ndim, vector.shape

(1, torch.Size([2]))

In [76]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]]) 
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [77]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 2]))

In [78]:
MATRIX[1]

tensor([ 9, 10])

In [79]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [80]:
TENSOR.ndim, TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [81]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers -> Look at the data -> Update the random numbers ->`
https://pytorch.org/docs/stable/generated/torch.rand.html

In [82]:
# Random tensors of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5196, 0.6742, 0.2247, 0.3018],
        [0.7927, 0.1940, 0.0595, 0.0662],
        [0.2653, 0.8300, 0.3513, 0.9672]])

In [83]:
random_tensor.ndim

2

In [84]:
# Create a random tensor with a similar shape to an image tensor

# height, width, color channels
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim  

(torch.Size([224, 224, 3]), 3)

 ### Zeros and Ones

In [85]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [86]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [87]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [88]:
ones.dtype  # data type

torch.float32

### Creating a range of tensors and tensors-like

1. torch.arange
https://pytorch.org/docs/stable/generated/torch.arange.html

In [89]:
# Use torch.range()
torch.range(0,10)

/tmp/ipykernel_17507/3858421243.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [90]:
# Use torch.arange()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

https://pytorch.org/docs/stable/tensors.html

https://en.wikipedia.org/wiki/Precision_(computer_science)

**Note:** Tensor datatypes is one of the three big errors people often run into with PyTorch & Deep Learning
1. Tensors not right dataytpes
2. Tensors not right shape
3. Tensors not on the right device


In [92]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=None, # float16, float32, etc.
                               device="cuda",
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [93]:
float_32_tensor.dtype

torch.float32

In [94]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [95]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [96]:
(float_16_tensor * float_32_tensor).dtype

torch.float32

In [97]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32, device='cuda')
int_32_tensor, int_32_tensor.dtype

(tensor([3, 6, 9], device='cuda:0', dtype=torch.int32), torch.int32)

In [98]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

### Getting information from tensors

1. Tensors not right dataytpes - dtype
2. Tensors not right shape     - shape
3. Tensors not on the right device   - device


In [99]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8788, 0.8336, 0.3652, 0.8572],
        [0.8139, 0.9811, 0.4684, 0.6634],
        [0.4436, 0.7270, 0.1853, 0.3581]])

In [100]:
# Get the details about the some tensor
print(some_tensor)
print(f'Datatype of the tensor: {some_tensor.dtype}')
print(f'Shape of the tensor: {some_tensor.shape}')
print(f'Device of the tensor: {some_tensor.device}')
print(f'Size of the tensor: {some_tensor.size()}')  # size is a function

tensor([[0.8788, 0.8336, 0.3652, 0.8572],
        [0.8139, 0.9811, 0.4684, 0.6634],
        [0.4436, 0.7270, 0.1853, 0.3581]])
Datatype of the tensor: torch.float32
Shape of the tensor: torch.Size([3, 4])
Device of the tensor: cpu
Size of the tensor: torch.Size([3, 4])


### Manipulation of Tensors(tensor operations)

- Addition
- Subtraction
- Multiplication(element-wise)
- Division
- Matrix mulitiplication


In [101]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [102]:
tensor * 10

tensor([10, 20, 30])

In [103]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [104]:
tensor - 10 

tensor([-9, -8, -7])

In [105]:
# Try out PyTorch in-built function
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [106]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Two different ways of Multiplication

- Element wise multiplication
- Matrix multiplication  (Dot Product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match
  * (3,2) @ (3,2)❌ 
  * (2,3) @ (3,2)✅
  * (3,2) @ (2,3)✅

2. The resulting matrix has the shape of the **outer dimensions**
  * (2,3) @ (3,2) - (2,2)
  * (3,2) @ (2,3) - (3,3)

In [107]:
# Element wise 
print(tensor, "*", tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [108]:
# Dot Product
print(tensor, " dot ", tensor)
print(f'Equals: {tensor.dot(tensor)}')

tensor([1, 2, 3])  dot  tensor([1, 2, 3])
Equals: 14


In [109]:
# Matrix multiplication
print(tensor, " multiply ", tensor)
print(f'Equals: {tensor.matmul(tensor)}')
print(f'Also equals: {torch.matmul(tensor, tensor)}')

tensor([1, 2, 3])  multiply  tensor([1, 2, 3])
Equals: 14
Also equals: 14


In [110]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 939 µs, sys: 292 µs, total: 1.23 ms
Wall time: 641 µs


tensor(14)

In [111]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 41 µs, sys: 0 ns, total: 41 µs
Wall time: 45.8 µs


tensor(14)

In [112]:
%%time
tensor.matmul(tensor)

CPU times: user 374 µs, sys: 0 ns, total: 374 µs
Wall time: 298 µs


tensor(14)

In [113]:
%%time
tensor.dot(tensor)

CPU times: user 171 µs, sys: 53 µs, total: 224 µs
Wall time: 176 µs


tensor(14)

### One of the most common erros in deep leanring - shape erros


In [114]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2,],
                          [3,4],
                          [5,6]])
tensor_B = torch.tensor([[7,10,],
                          [8,11],
                          [9,12]])


In [115]:

#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul(alias)
torch.matmul(tensor_A, tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [116]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [117]:
tensor_B.T, tensor_B

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]))

In [118]:
tensor_A.shape, tensor_B.T.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [119]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [120]:
result = torch.matmul(tensor_A, tensor_B.T)
result.shape

torch.Size([3, 3])

### Finding the min, max, mean, sum, etc(tensor aggregation)

In [121]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [122]:
# min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [123]:
# max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [124]:
# mean
torch.mean(x)

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Long instead.

In [125]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [126]:
# sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [127]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [128]:
x.argmin()

tensor(0)

In [129]:
x.argmax()

tensor(9)

In [130]:
x[x.argmin()], x[x.argmax()]

(tensor(0), tensor(90))

### Reshaping, stacking, squeezing, and unsqueezing tetnsors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other(vstack, hstack)

https://pytorch.org/docs/stable/generated/torch.hstack.html
https://pytorch.org/docs/stable/generated/torch.vstack.html

* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze -add a '1' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain  way



In [131]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [132]:
# Add an extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [133]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [134]:
# Changing z will chhange the x too (because a view of a tensor shares the same meomory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [135]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked, x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [136]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked, x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]),
 torch.Size([9, 4]))

In [140]:
# Squeeze, and Unqueeze

x_reshaped, x_reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [141]:
x_reshaped.squeeze().shape

torch.Size([9])

In [144]:
torch.squeeze(x_reshaped).shape

torch.Size([9])

In [150]:
x_reshaped.squeeze().shape, x_reshaped.squeeze().unsqueeze(dim=0).shape

(torch.Size([9]), torch.Size([1, 9]))

In [154]:
x_reshaped.squeeze().unsqueeze(dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [153]:
x_reshaped.squeeze().unsqueeze(dim=1)

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [158]:
# torch.permute  - rearrange the dimensions 
x_original = torch.rand(size=(224,224,3)) # height, width, color

# permute the original tensor to rearrange the axis( or dim) order
x_permuted = x_original.permute(2,0,1)
x_permuted.shape

torch.Size([3, 224, 224])

In [160]:
x_original[:, :, 0].shape

torch.Size([224, 224])

In [162]:
x_permuted[:, :, 0].shape

torch.Size([3, 224])

### Indexing(selecting data from tensors)
Indexing with PyTorch is similar to indexing with Numpy

In [163]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [164]:
x[0][0]

tensor([1, 2, 3])

In [165]:
x[0][0][0]

tensor(1)

In [167]:
# Get number 9
x[0][2][2].item()

9

In [168]:
# You can also use ":" to select all of the target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [169]:
# Get all the values of the 0th and 1sts dimensions 
# but the only the index 1 of the 2nd dimension
x[:, :, 1]  

tensor([[2, 5, 8]])

In [170]:
# Get all values of the 0 dimension but only the 1 index value 
# of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [171]:
# Index on x to return 3,6,9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & Numpy

In [172]:
import torch
import numpy as np

In [174]:
# When converting from numpy-> pytroch, 
# pytroch reflects numpy's default datatype of float64,
# potential datatype issue may occur

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [175]:
tensor.dtype

torch.float32

In [176]:
# Change the value of array
array = array + 1

In [178]:
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [179]:
# Tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [180]:
# Change the tensor, what happens to numpy_tensor
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take random out of random)  

In short how a neural network learns:  
`Start with random nums -> tensor operations -> update random numbers to try and make them of the data -> again - again -> ...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

In [184]:
import torch

In [185]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9173, 0.6798, 0.9450, 0.3178],
        [0.4970, 0.0088, 0.7917, 0.0344],
        [0.7457, 0.1929, 0.7859, 0.4641]])
tensor([[0.3681, 0.8062, 0.5706, 0.8713],
        [0.3074, 0.9634, 0.2706, 0.0137],
        [0.4998, 0.4857, 0.5615, 0.1857]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [199]:
# Making some random but reproducible tensors

# Set the random seed
RANDOM_SEED = 42

In [200]:
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

In [201]:
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

In [202]:
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs

In [203]:
import torch

In [204]:
torch.cuda.is_available()

True

In [205]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [206]:
device

'cuda'

In [207]:
torch.cuda.device_count()

1

In [209]:
tensor = torch.tensor([1,2,3])
tensor.device

device(type='cpu')

In [223]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### Moving tensors back to the cpu


In [217]:
tensor_on_gpu.device

device(type='cuda', index=0)

In [218]:
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [226]:
tensor_on_cpu = tensor_on_gpu.to('cpu')
tensor_on_cpu, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [232]:
tensor_on_cpu.numpy()

array([1, 2, 3])

In [234]:
# numpy to list
tensor_on_cpu.numpy().tolist()

[1, 2, 3]

In [237]:
tensor_on_gpu.cpu().device

device(type='cpu')